sudo: false
language: rust
rust: stable
cache: cargo
# os:
#   - linux
#   - osx
before_install:
  - nvm install stable
script:
  - cargo install --root . pax
after_success:
  - ./publish.sh linux
notifications:
  email:
    on_success: never
